# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Sean Grehan
  email: G00405094@atu.ie
description: "Digital Rain Project."

# Build settings
remote_theme: jekyll/minimal-mistakes
